services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: "${MONGO_URI}"
      MONGO_DB: "${MONGO_DB}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - database
    image: go_chat_backend:dev
    develop:
      watch:
        - path: ./src
          action: rebuild

  database:
    image: mongo:8.2
    container_name: go_chat-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: